/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as KgorosoRouteImport } from './routes/kgoroso'
import { Route as GiftRegistryRouteImport } from './routes/gift-registry'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const KgorosoRoute = KgorosoRouteImport.update({
  id: '/kgoroso',
  path: '/kgoroso',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftRegistryRoute = GiftRegistryRouteImport.update({
  id: '/gift-registry',
  path: '/gift-registry',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/gift-registry': typeof GiftRegistryRoute
  '/kgoroso': typeof KgorosoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/gift-registry': typeof GiftRegistryRoute
  '/kgoroso': typeof KgorosoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/gift-registry': typeof GiftRegistryRoute
  '/kgoroso': typeof KgorosoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gallery' | '/gift-registry' | '/kgoroso' | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gallery' | '/gift-registry' | '/kgoroso' | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/gallery'
    | '/gift-registry'
    | '/kgoroso'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRoute: typeof GalleryRoute
  GiftRegistryRoute: typeof GiftRegistryRoute
  KgorosoRoute: typeof KgorosoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kgoroso': {
      id: '/kgoroso'
      path: '/kgoroso'
      fullPath: '/kgoroso'
      preLoaderRoute: typeof KgorosoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-registry': {
      id: '/gift-registry'
      path: '/gift-registry'
      fullPath: '/gift-registry'
      preLoaderRoute: typeof GiftRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRoute,
  GiftRegistryRoute: GiftRegistryRoute,
  KgorosoRoute: KgorosoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
